
POST http://localhost:3000/api/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NWNmNGUxNTk0YTdmZjJjMWQ3NGVkZiIsImlhdCI6MTcwMjQ2MTc5NywiZXhwIjoxNzAyNTQ4MTk3fQ.SItCozXj40hQy67vytrr70smzr-0qCa3uVOm6wNUhKM

{
    "firstName":"nati",
    "lastName":"Abera",
    "phoneNumber":"0912211221",
    "email":"email@gmail.com",
    "password":"12345678"
}
###

GET http://localhost:3000/api/user?perPage=4&page=3
Content-Type: application/json

###

GET http://localhost:3000/api/user/65ae7fba71b64b79ea0241a3
Content-Type: application/json

###

PUT http://localhost:3000/api/user/65ae7fba71b64b79ea0241a3
Content-Type: application/json

{
    "firstName":"natiaaaaaaaaaaaaa",
    "lastName":"Abera",
    "phoneNumber":"0912211221"
}

###

DELETE  http://localhost:3000/api/user/65ae7fba71b64b79ea0241a3
Content-Type: application/json

###

POST http://localhost:3000/api/user/login
Content-Type: application/json

{
    "email":"email5@gmail.com",
    "password":"12345678"
}
###

GET http://localhost:3000/api/product/?perPage=10&page=1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YWVhYjI5MzFkOTMzMzU1MWVlMGE0NiIsImlhdCI6MTcwNjA5Mzg5OCwiZXhwIjoxNzA2NTI1ODk4fQ.kgkNNkuwToBbSaWwhGwdOfRuo1rDb6PNMPTC6C2idQY

###
GET http://localhost:3000/api/product/?search=opal
Content-Type: application/json

###
POST http://localhost:3000/api/product
Content-Type: application/json

###
DELETE http://localhost:3000/api/product/65aff2275550f0c2d7504ef0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YWVhYjI5MzFkOTMzMzU1MWVlMGE0NiIsImlhdCI6MTcwNjA5Mzg5OCwiZXhwIjoxNzA2NTI1ODk4fQ.kgkNNkuwToBbSaWwhGwdOfRuo1rDb6PNMPTC6C2idQY

###

GET http://localhost:3000/api/product/65b15fe19bce048f17defdef
Content-Type: application/json


